"""initial schema

Revision ID: d1b4f5cbf7e7
Revises: 
Create Date: 2026-09-06 12:57:37.939008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1b4f5cbf7e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_hi', sa.String(length=120), nullable=True),
    sa.Column('name_te', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_en')
    )
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_hi', sa.String(length=120), nullable=True),
    sa.Column('name_te', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_en')
    )
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_hi', sa.String(length=120), nullable=True),
    sa.Column('name_te', sa.String(length=120), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_en', 'state_id', name='uq_district_state')
    )
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=False),
    sa.Column('name_hi', sa.String(length=160), nullable=True),
    sa.Column('name_te', sa.String(length=160), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('variety', sa.String(length=120), nullable=True),
    sa.Column('grade', sa.String(length=40), nullable=True),
    sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('modal_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_records', schema=None) as batch_op:
        batch_op.create_index('ix_price_lookup', ['crop_id', 'market_id', 'price_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_records', schema=None) as batch_op:
        batch_op.drop_index('ix_price_lookup')

    op.drop_table('price_records')
    op.drop_table('markets')
    op.drop_table('districts')
    op.drop_table('states')
    op.drop_table('crops')
    # ### end Alembic commands ###
